### ISSUE TITLE
Don't use strcasecmp() to compare options arguments

### ISSUE THREAD

**Issue by martinezjavier** [intel/tpm2-tools#514]
Some tools like tpm2_evictcontrol and tpm2_encryptdecrypt compare options arguments passed to the tool ignoring the case. There's no point to do this since the correct values should be properly documented in the manual pages for the tools.

**Comment by williamcroberts** [comment]
Issue #614 reduces this issue to just:
```
tpm2_evictcontrol.c:104:        if (!strcasecmp(value, "o")) {
tpm2_evictcontrol.c:106:        } else if (!strcasecmp(value, "p")) {
```

**Comment by williamcroberts** [comment]
Also looks like createprimary is doing the same thing, just harder:
```
tpm2_createprimary.c:206:        if(strcmp(value, "o") == 0 || strcmp(value, "O") == 0)
tpm2_evictcontrol.c:104:        if (!strcasecmp(value, "o")) {
```
