### ISSUE TITLE
Improve tpm2_encryptdecrypt -D, --decrypt option

### ISSUE THREAD

**Issue by martinezjavier** [intel/tpm2-tools#515]
The tool has a -D, --decrypt option that tells it if the operation should be encryption or decryption. But it's not only confusing since the user has to provide "-D YES" or "-D NO" but also this isn't documented in the man page.

It should be changed to either just require -D in the case of decryption and default to encryption or allow the user to explicitly specify the operation (i.e: -D or -E).

**Comment by williamcroberts** [comment]
defaults to encrypt without -D seems reasonable to me.

**Comment by williamcroberts** [comment]
duplicated by #614 and fixed.
