### ISSUE TITLE
TPM locks up after many reboots

### ISSUE THREAD

**Issue by pskindel** [intel/tpm2-tools#583]
Using latest stable release of TPM stack:
- tpm2-tss 1.2.0
- tpm2-abrmd 1.1.1
- tpm2-tools 2.1.0

TPM chip locks up (dictionary attack lock) after every 30. reboot. I can't find a way to unlock it using provided tools.

In master there is `tpm2_dictionarylockout` tool, which invoked with `-c` option successfully unlocks chip. But it still sounds like a workaround to invoke this tool every 30. reboot. Also this tool is only available in master branch, which is considered unstable and it is incompatible with latest stable, so I cannot use it in production.

According to https://github.com/01org/tpm2-tss/issues/480, https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf (section 19.8.6) and https://rd.springer.com/book/10.1007%2F978-1-4302-6584-9 (page 302) TPM should be properly informed before system shutdown (_TPM2_Shutdown with the CLEAR option followed by TPM2_Startup with the CLEAR option._).

There is _tpm2_startup_ tool, but it is not enough to invoke it after every boot with `--clear` flag to protect against DA locks (tested).

Is there any way to prevent these locks using tpm tools?

**Comment by martinezjavier** [comment]
@pskindel as @flihp mentions in the 01org/tpm2-tss#480 you shared, this seems like a TPM kernel 
 (or firmware) device driver bug to me. What Linux kernel version are you using?

**Comment by webmeister** [comment]
There is support for automatically [sending TPM2_Shutdown in the kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/char/tpm?id=d1bd4a792d3961a04e6154118816b00167aad91a). But that is probably not part of your kernel. Could you try it with a newer version (4.13+)?

**Comment by martinezjavier** [comment]
@snits any comment on this? Since you are much more familiar with the kernel side of the TPM2 support and also I guess with the CentOS 7.4 kernel used by @pskindel.

**Comment by idesai** [comment]
@pskindel can you please increase the "max-tries" parameter from default 3 to 10. you can use the dictionary lockout tool to set it up. Looks like the TPM is going through in-orderly shutdown more often in the reboot process.

**Comment by williamcroberts** [comment]
This seems to be a TPM issue not a tools issue coupled with a question. Closing.

**Comment by pskindel** [comment]
I have successfully resolved the problem. I've written additional tool `tpm2_shutdown`, similar to `tpm2_startup`. Calling `tpm2_startup --clear` after boot and `tpm2_shutdown --clear` right before shutdown protects from TPM dictionary locks.

**Comment by pijopenchev** [comment]
Hello, did this `tpm2_shutdown` tool ever go in? I don't see it on the master branch under /tools. Having the same issue on Ubuntu 16.04( 4.10.0-42-generic ). Would love to solve it this way rather than unlocking the TPM via `tpm2_dictionarylockout -c`. 
Thanks!

**Comment by williamcroberts** [comment]
No it hasn't. @pskindel you want to submit that tool to master?
