### ISSUE TITLE
move from 3.X to master

### ISSUE THREAD

**Issue by williamcroberts** [intel/tpm2-tools#616]
Take commits fixing issues #305 and #306 to master after the 3.X PR is merged: https://github.com/intel/tpm2-tools/pull/613

**Comment by martinezjavier** [comment]
I don't think you meant #305 and #306. Are those really the correct issues numbers?

**Comment by williamcroberts** [comment]
I think I meant #605 and #606

**Comment by williamcroberts** [comment]
Looks like #606 was on c9505af9

**Comment by williamcroberts** [comment]
#605 will be here: https://github.com/intel/tpm2-tools/pull/617
