### ISSUE TITLE
bad size calculation in `tpm2_convert_pubkey`

### ISSUE THREAD

**Issue by flihp** [intel/tpm2-tools#635]
https://github.com/intel/tpm2-tools/blob/master/lib/conversion.c#L92

The `sizeof` builtin will return the size of the structure, not the size of the data in the structure. The TPM2B_PUBLIC structure has a size field for this purpose.

**Comment by flihp** [comment]
I don't think using the 'size' field from the structure is the right solution here. This size will not be sufficient if we're dumping the structure as a byte array (buffers internal to this structure may not be fully populated). We should probably use the type marshalling functions instead.

**Comment by williamcroberts** [comment]
We're going to use libmarshal to get a proper byte array
