### ISSUE TITLE
Mix of endianness and padding in serialized quote-related output

### ISSUE THREAD

**Issue by lockcmpxchg8b** [intel/tpm2-tools#636]
The "quote file" output from tpm2_quote is a little-endian TPM2B header over a wholly big-endian TPMS_ATTEST structure, followed by a little-endian TPMT_SIGNATURE.

To validate this quote, one also needs the contents of the ak.pub as produced tpm2_getpubak.  Access to the AK data is supposed to be made easier via tpm2_akparse, but this tool doesn't output the curve (for ECDSA) in its nicely formatted output.  For that, one must attempt to parse ak.pub, which is consistently little-endian, but is not a proper serialization (e.g., there are many cases of struct-alignment padding being included in the file).

To be specific, github presently contains:
**tpm2_getpubak.c:384**
```
    /* TODO fix this serialization */
    result = files_save_bytes_to_file(ctx.output_file, (UINT8 *) &out_public, sizeof(out_public));
```
So...what is the desired serialization format?  Should it be the de facto crypto standard big-endian?  Is there a reason ECC_PARAMETERS serialize their entire MAX_ECC_KEY_BYTES size rather than their TPM2B length?  If someone were to submit a pull request, what would the maintainers want to see in it?

**Comment by martinezjavier** [comment]
@lockcmpxchg8b this is a bug on how the tool serialize its output. Take a look to the current discussion in https://github.com/intel/tpm2-tools/pull/630.

**Comment by williamcroberts** [comment]
Yeah this should use the libmarshal routine for that struct

**Comment by martinezjavier** [comment]
@williamcroberts it's that something you or @flihp are already looking at or do you want help with that?

**Comment by williamcroberts** [comment]
Not tpm2_getpubak, so if you want to do it, go ahead.

**Comment by martinezjavier** [comment]
@williamcroberts I was asking in general. Probably makes more sense for a single person to just fixes all the serializations since I guess all the change for each tool will be similar.
