### ISSUE TITLE
fix TODO serialize issues

### ISSUE THREAD

**Issue by williamcroberts** [intel/tpm2-tools#639]
Fix all the todo's regarding serialization of structures to disk.

**Comment by williamcroberts** [comment]
The -r option to load_external is untested, fixup the serialize for -r to use libmarshal. Not sure how to test it.

**Comment by lockcmpxchg8b** [comment]
Would it be feasible to add a serialization_version number to top-level serialized structures?

Otherwise we may quickly reach a state where the consumer of a TPM remote attestation needs to know what version of TPM2.0-tools was used on the remote side.

**Comment by martinezjavier** [comment]
@lockcmpxchg8b my understanding is that the idea is to fix this for good now.

So what you would have serialized is the structures as defined in the TPM spec. So if everything goes well it shouldn't have to changed in the future.
