### ISSUE TITLE
tpm2_create -o option not working

### ISSUE THREAD

**Issue by iolivergithub** [intel/tpm2-tools#648]
$tpm2_create -c po.ctx -P ... -K ... -g 0x000b -G 0x0001 -o k.pub -O k.priv
tpm2_create: unrecognized option '-o'
ERROR: Unkown Argument:

The options are -u and -r respectively.

However,

$tpm2_createprimary -A e -K xyz123 -g 0x000b -G 0x0001 -C po.ctx -P xyz123
is successful returning po.ctx, object attribute and handle (eg: 0x800000ff)

$tpm2_create -c po.ctx -P xyz123-K xyz123 -g 0x000b -G 0x0001 -u k.pub -r k.priv
returns a context load error: 0x902

$tpm2_create -H  0x800000ff -P xyz123-K xyz123 -g 0x000b -G 0x0001 -u k.pub -r k.priv
returns an object attrbiute but erro 0x184

**Comment by martinezjavier** [comment]
@iolivergithub first of all, what version of the tools are you using?

The `-o` option has been deprecated in favour of the `-u` option as you mention. So I don't understand the issue subject.

> $tpm2_createprimary -A e -K xyz123 -g 0x000b -G 0x0001 -C po.ctx -P xyz123
> is successful returning po.ctx, object attribute and handle (eg: 0x800000ff)

I wonder how the primary key creation worked for you, since in both 3.x and master the `-A` option is now `-H`.

> $tpm2_create -c po.ctx -P xyz123-K xyz123 -g 0x000b -G 0x0001 -u k.pub -r k.priv
> returns a context load error: 0x902

There is a tpm2_rc_decode tool that decodes the TPM response codes, this will help you understand what's going on:

```
$ tpm2_rc_decode 0x902               
error layer                 
  hex: 0x0                  
  identifier: TSS2_TPM_ERROR_LEVEL                      
  description: Error produced by the TPM                
format 0 warning code       
  hex: 0x02                 
  name: TPM2_RC_OBJECT_MEMORY                           
  description: out of memory for object contexts
```
It says that the TPM doesn't have more free memory to store transient objects in its RAM. This is usually the case when you are not using a resource manager.

> $tpm2_create -H 0x800000ff -P xyz123-K xyz123 -g 0x000b -G 0x0001 -u k.pub -r k.priv
> returns an object attrbiute but erro 0x184

I believe this issue is the same than the one reported in #489.

**Comment by iolivergithub** [comment]
Hi,

I'm using 2.1.0 where the A option is still valid

  case 'A':
        if(strcmp(value, "o") == 0 || strcmp(value, "O") == 0)
            ctx.hierarchy = TPM_RH_OWNER;
        else if(strcmp(value, "p") == 0 || strcmp(value, "P") == 0)
            ctx.hierarchy = TPM_RH_PLATFORM;
        else if(strcmp(value, "e") == 0 || strcmp(value, "E") == 0)
            ctx.hierarchy = TPM_RH_ENDORSEMENT;
        else if(strcmp(value, "n") == 0 || strcmp(value, "N") == 0)
            ctx.hierarchy = TPM_RH_NULL;
        else {
            LOG_ERR("Invalid hierarchy, got\"%s\"", value);
            return false;
        }
        ctx.flags.A = 1;
        break;

I tried setting the TCTI options to point to /dev/tpmrm0 but without success. Will recompile the tools etc to the latest version and go through this process again.

**Comment by iolivergithub** [comment]
OK. Downloaded the 3.X branch but this will not compile against the current tss version (requires sapi with version < 2,  latest tss has sapi 2.0.0-dev )

Latest tools-master reports during make:

gcc: error: 1.0.0: No such file or directory
Makefile:1560: recipe for target 'tools/tpm2_activatecredential' failed
make: *** [tools/tpm2_activatecredential] Error 1

tss, tools and abrmd all master versions

**Comment by martinezjavier** [comment]
@iolivergithub yes, 3.X has to be built against the latest stable version of tpm2-tss (1.3.0-rc2) and tpm2-tools master against tpm2-tss master.

Now, regardless your original issue. I believe you were not using the tpm2-tools 2.1.0 version. Since I just built it from source (against tpm2-tss 1.2.0) and it worked for me:

```
$ export TPM2TOOLS_TCTI_NAME=device

$ export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0 

$ tpm2_takeownership -e xyz123                                        

$ tpm2_createprimary -A e -K xyz123 -g 0x000b -G 0x0001 -C po.ctx -P xyz123                                                                                                    
nameAlg = 0x000b                                        
type = 0x0001                                           
contextFile = po.ctx                                    

CreatePrimary Succeed ! Handle: 0x80ffffff 

$ tpm2_create -c po.ctx -P xyz123 -K xyz123 -g 0x000b -G 0x0001 -o k.pub -O k.priv
contextParentFile = po.ctx
nameAlg = 0x000b
type = 0x0001
ObjectAttribute: 0x00060072

Create Object Succeed !
```
Note that I'm using the `-o` and `-O` options as supported by this version of the tool

**Comment by martinezjavier** [comment]
$ tpm2_takeownership -v
tpm2_takeownership, version 2.1.0-2-gc8440f6a3be6

**Comment by martinezjavier** [comment]
> Latest tools-master reports during make:
> 
> gcc: error: 1.0.0: No such file or directory
> Makefile:1560: recipe for target 'tools/tpm2_activatecredential' failed
> make: *** [tools/tpm2_activatecredential] Error 1

A silly question but did you clean your build dir, re-ran the configure script, etc after checking out the latest master?

**Comment by martinezjavier** [comment]
@iolivergithub this doesn't seem to be an issue with the tools but a build problem at your end. Could you please close the issue and we can move the discussion to the https://lists.01.org/mailman/listinfo/tpm2 mailing list that's mean for user questions. Thanks!

**Comment by iolivergithub** [comment]
As of now...redownloaded the 3 master versions of tss, abrmd and tools ... tss and tools compile, abrmd fails - though an earlier version worked and abrmd is running  (instructions followed to the letter - have the full transcript of the compile available).

And yes, in all cases the builds were clean, bootstrap, configure etc etc.

This is what I get for the takeownership -v:

310$tpm2_takeownership -v
tool="tpm2_takeownership" version="" tctis="tabrmd,socket,device,"

Different attempt:

tpm2-tss-1.3.0-rc2  compiles successfully
tpm2-tools-3.0.rc1  does not (against the above)  - and neither does tpm2-tools-master now...

Which versions do work against each other?   I have the tools working but at this point I'm not convinced the whole installation is "sane"

Discussion moving to mailing list...

**Comment by martinezjavier** [comment]
@iolivergithub Ok, let's move the conversation to the mailing list. Could you please close the issue?
