### ISSUE TITLE
tpm2_load fails to work after reboot

### ISSUE THREAD

**Issue by arvindiotium** [intel/tpm2-tools#691]
I installed tpm2-tss, tpm2-tools, tpm2-tools from latest master and created a persistent handle, 0x81010009, in order to persist primary context. I’m using endorsement hierarchy. Encryption/Decryption works correctly using tpm2_rsaecnrypt and tpm2_rsadecnrypt. But, after rebooting my linux machine, tpm2_load errors out with error code 0x1df. Is there a fix available for this issue ?

A. tpm_load output
# tpm2_load -H 0x81010009 -u pub.key -r priv.key -C ctx1
ERROR:
Load Object Failed ! ErrorCode: 0x1df

B. Error code
# tpm2_rc_decode 0x1df
error layer
hex: 0x0
identifier: TSS2_TPM_ERROR_LEVEL
description: Error produced by the TPM
format 1 error code
hex: 0x1f
identifier: TPM2_RC_INTEGRITY
description: integrity check failed
parameter
hex: 0x100
identifier: TPM2_RC_1
description: (null)

**Comment by martinezjavier** [comment]
@arvindiotium can you please share the exact sequence of commands you are using so your issue can be easily reproduced?

**Comment by martinezjavier** [comment]
This worked for me:

```bash
$ tpm2_createprimary -H e -g sha256 -G rsa -C primary.context                       
ObjectAttribute: 0x00030072                             

CreatePrimary Succeed ! Handle: 0x80ffffff

$ tpm2_evictcontrol -A o -c primary.context -S 0x81010009
persistentHandle: 0x81010009

$ tpm2_listpersistent 
persistent-handle[0]:0x81010009 key-alg:rsa hash-alg:sha256 object-attr:fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt

$ tpm2_create -g sha1 -G rsa -u obj.pub -r obj.priv -H 0x81010009                   
algorithm:
  value: sha1
  raw: 0x4
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type: 
  value: rsa
  raw: 0x1
  rsa: aac7e2bd76346cbf06e3b89ceacaacf51ef9eb4c1aac547bdf4d6483928c81c54c3855fef37de0d1d9a5f0be1722100d4b9667cb77c50bd1160bb177d566217f71f2a1a759e08e613eda63380b4e85129b9e09a150c0905c686983e86104df887290e763fa4c64f9477fbeb0381f111fcef68566e8dc744ac451668fed45e307ac0a63ab8b91959df381aa3847ecd8c3598c6b8b8c0cb18f7a77eba9069db338c7767d10ea96bdff7e60f80774da3e0fbf8cc7b716b76cd69454263730119c61e0cfead311d537da208eae639494e6181763a23084bf01902b948eb8e7c583b73d38a30eb8f321ca1f5107bdc961756ca06a25a213c2c8e4504879278b2bba0f

$ reboot

$ tpm2_load -H 0x81010009 -u pub.key -r priv.key -C load.context

Load succ.
LoadedHandle: 0x80ffffff
```
With an Intel PTT fTPM2.0 and using the in-kernel resource manager, what TPM2.0 chip are you using an which resource manager?

**Comment by arvindiotium** [comment]
Thanks for your reply, I'm not typing commands by hand, the sequence is run by code. I will share further details shortly. It's always reproducible.

**Comment by arvindiotium** [comment]
I was using wrong sequence of tpm commands in my code which cleared the persistent handle. Thanks for your support, I'm closing this issue.
