### ISSUE TITLE
Provide an alternative to man pages on embedded platforms

### ISSUE THREAD

**Issue by emmanuel-deloget** [intel/tpm2-tools#730]
This title does not mean that tpm2-tools shall provide a tool to view man pages on embedded platforms :)

But when man in not accessible it is not possible to see at least the list of option of any tool. 

On my board, 

```
root@eboard ~# tpm2_hash -h
ERROR: Could not execute "man tpm2_hash" error: No such file or directory
```

This doe snot help much :)

The proposed correction whould be to add a configure option to enable/disable usage texts within the tools, and to hack something to easily encode the purpose of the tool and of options (maybe by modifying tpm2_option_new() ?). 

BR, 

-- Emmanuel Deloget

**Comment by martinezjavier** [comment]
@emmanuel-deloget I was thinking about other the other day, that I think is related with this one.

The tools are not consistent on the information that's printed when executed without any options. If you execute the following, you will find a lot of inconsistent behaviours:

```
$ for tool in $(ls /usr/bin/tpm2_*); do echo $tool && $tool; done
```

Some tools don't print anything, other just try to be executed with wrong option values and the ones that do print something, use the following format:

```
$ tpm2_activatecredential 
ERROR: Expected options (H or c) and (k or C) and f and o
```

Which doesn't really says a lot....

I would like the tools to print a nice usage texts as you suggest, just like other CLI tools do:

```
$ ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           [user@]hostname [command]
```

So one solution for your issue is that if the man pages could not be built (i.e: no pandoc support in the platform), then `-h` could be taken as if no option where passed and print a nice usage summary.

What do you think?

**Comment by martinezjavier** [comment]
and yes, I also thought about passing this information in `tpm2_option_new()`.

**Comment by emmanuel-deloget** [comment]
You might cross build on a platform where pandoc is available, so that would only take care of a part of the problem - thus my idea of providing an option to the configure script which is, I think, a more robust solution to this issue.

**Comment by martinezjavier** [comment]
@emmanuel-deloget right, that was just an example. My point was about having a summary help text when using no option and have the possibility (with a configure option as you suggest) to make `--help` fallback to that.

**Comment by emmanuel-deloget** [comment]
Sounds good to me :)

**Comment by martinezjavier** [comment]
@williamcroberts what do you think about it? I can add to my TODO list if you agree with the idea.

**Comment by williamcroberts** [comment]
We took out inline docs from the tools due to having to duplicate the information between the tool source and the manpages.

I would be interested in:
1. cleaning up help output in the tools
2. inlining the documentation in the tools as long as it's single source. Maybe you could put together a system that generates the manpages and generates the inline documentation in the tool from a single source.

Thoughts, overkill?

**Comment by emmanuel-deloget** [comment]
@williamcroberts point 2 sounds interesting, but that would require to put the whole help text for each option within the source code (and that would need a tool to get this text in a markdown format ; after that, including the generated text in the manpage md files is trivial).

**Comment by martinezjavier** [comment]
@williamcroberts I'm not sure if such a system will cause more harm than good. It would had make more sense in the last months that there was a lot of churn in the tool options / man pages.

But I think that stuff has settled down a little bit and I don't expect a lot of changes anymore. @emmanuel-deloget has done a very necessary cleanup so I think the options are in a better shape now.

What about using the struct options array to generate the output? For example we could have something like the following:

```
diff --git a/tools/tpm2_tool.c b/tools/tpm2_tool.c
index 4a0a8eac50e8..b3a63169dffd 100644
--- a/tools/tpm2_tool.c
+++ b/tools/tpm2_tool.c
@@ -101,6 +101,7 @@ static TSS2_SYS_CONTEXT* sapi_ctx_init(TSS2_TCTI_CONTEXT *tcti_ctx) {
 int main(int argc, char *argv[], char *envp[]) {
 
     int ret = 1;
+    unsigned int i;
 
     tpm2_options *tool_opts = NULL;
     if (tpm2_tool_onstart) {
@@ -111,6 +112,21 @@ int main(int argc, char *argv[], char *envp[]) {
         }
     }
 
+    if (argc == 1 && tool_opts) {
+           tpm2_tool_output("usage: %s\n", argv[0]);
+           for (i = 0; i < tool_opts->len; i++) {
+                   struct option *opt = &tool_opts->long_opts[i];
+                   tpm2_tool_output("[ -%c %s ] ", opt->val, opt->name);
+                   if (i && i % 4 == 0) {
+                           tpm2_tool_output("\n");
+                   } else {
+                           tpm2_tool_output(" ");
+                   }
+           }
+           tpm2_tool_output("\n");
+           return ret;
+    }
+
     tpm2_option_flags flags = { .all = 0 };
     TSS2_TCTI_CONTEXT *tcti;
     tpm2_option_code rc = tpm2_handle_options(argc, argv, envp, tool_opts, &flags, &tcti);
```

```
$ tpm2_getmanufec 
usage: tpm2_getmanufec
[ -e endorse-passwd ]  [ -o owner-passwd ]  [ -H handle ]  [ -P ek-passwd ]  [ -g alg ] 
[ -f output ]  [ -N non-persistent ]  [ -O offline ]  [ -E ec-cert ] 
[ -U SSL-NO-VERIFY ]  [ -S input-session-handle ]

$ tpm2_flushcontext 
usage: tpm2_flushcontext
[ -H handle ]  [ -t transient-object ]  [ -l loaded-session ]  [ -s saved-session ]
```

And fallback to that if `-h` is passed using a configure option as @emmanuel-deloget suggested. It won't have all the information of the man page but it's a middle ground between having some info an 0 maintenance cost.

We probably will need a flag though for tools to say that they can be executed with no options, for example that's the case for `tpm2_listpersistent` and `tpm2_nvlist`.

**Comment by emmanuel-deloget** [comment]
@williamcroberts @martinezjavier it looks good ; wouldn't it be better in the form `[-H|--handle <VALUE>]`  when a parameter is required or `[-c|--clear]` when the option doesn't need any parameter ?

**Comment by martinezjavier** [comment]
@emmanuel-deloget oh yes, it was just a quick hack to discuss the idea so I haven't thought too much about the format. But I can propose as a formal pull request and we can discuss the details there.

I probably will do it tomorrow though since I'm busy with other stuff today.

**Comment by williamcroberts** [comment]
@martinezjavier I like that, good idea.
