### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by yunusemreayhan** [intel/tpm2-tools#742]
Error log : 
```
>>> tpmtsstools 3.0.2 Building
/usr/bin/make -j1 -C /home/change/maxim-ic/lde-3.0/TREE/user/buildroot/build/tpmtsstools-3.0.2 
Makefile:2304: *** missing separator.  Stop.
make[2]: *** [/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/build/tpmtsstools-3.0.2/.stamp_built] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/change/maxim-ic/lde-3.0/TREE/user/buildroot'
make: *** [rootfs-build] Error 2
make: Leaving directory `/home/change/maxim-ic/lde-3.0'
ldecmd build usip-0.2.3: *** ERROR 2, command failed: make -C /home/change/maxim-ic/lde-3.0 rootfs
/home/change/bin/ldecmd v1.0.2: *** ERROR 2, command failed: build rootfs
/home/change/maxim-ic/lde-3.0/TREE/user/buildroot/build/tpmtsstools-3.0.2
```
When I look at Makefile:2304 it is the line that @CODE_COVERAGE_RULES@ : 
```
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
#;**********************************************************************;
@CODE_COVERAGE_RULES@

man/man1/%.1 : man/%.1.md $(MARKDOWN_COMMON_DEPS)
	$(AM_V_GEN)rm -f $@ && \
	mkdir -p man/man1 && \
	sed -e '/\[common options\]/r man/common/options.md' \
	    -e '/\[common options\]/d' \
	    -e '/\[common tcti options\]/r man/common/tcti.md' \
	    -e '/\[common tcti options\]/d' \
	    -e '/\[password formatting\]/r man/common/password.md' \
```
Is this about my make version or something?
How can I fix this?
Thanks in advance

**Comment by emmanuel-deloget** [comment]
You are missing an aclocal macro. You shall install the **autoconf-archive** package (compiling tpm2-tools requires the following m4 files: 

```
ax_check_preproc_flag.m4
ax_check_link_flag.m4
ax_check_compile_flag.m4
ax_code_coverage.m4
```

Future updates might require further m4 files.

**Comment by yunusemreayhan** [comment]
thanks, i see

**Comment by osresearch** [comment]
Is there some way to improve the error reported for this dependency? I ran into a similar `bootstrap.sh` failure on a fresh Ubuntu 20.04 build and it was not easy to track down this issue to find that `apt install autoconfig-archive` would fix it (the `docs/INSTALL.md` mentions building autoconf-archive from source, but for ubuntu 16.04, which is a bit old now)

**Comment by williamcroberts** [comment]
> Is there some way to improve the error reported for this dependency? I ran into a similar `bootstrap.sh` failure on a fresh Ubuntu 20.04 build and it was not easy to track down this issue to find that `apt install autoconfig-archive` would fix it (the `docs/INSTALL.md` mentions building autoconf-archive from source, but for ubuntu 16.04, which is a bit old now)

just for bootstrap.sh to work it needs to call autoreconf, which will require that the m4 stuff works out, ie the version is good enough. If their is a portable way of checking autoconf-archive version in configure.ac or in the shell script before autoreconf is called, I would be open to it. But some folks just copy the m4 files they need from autoconf-archive manually, thus you don't even need autoconf-archive installed.

I'd be open to suggestions, but offhand I don't know of any good way of making the error more explicit.
