### ISSUE TITLE
Signing without hashing?

### ISSUE THREAD

**Issue by rautammi** [intel/tpm2-tools#753]
Would it be possible to add an option to tpm2_sign for providing just a message digest instead of the original message? When signing with a non-restricted key, it's not mandatory to have TPM to hash the message.

**Comment by williamcroberts** [comment]
@rautammi I don't see why not.

**Comment by emmanuel-deloget** [comment]
I am working on a tentative implementation for this (small) feature. What would be the prefered use case?

From what I understand, the -t option will not be provided and a new option will be used to specify the digest (-D, as in tpm2_verifysignature?).
