### ISSUE TITLE
CERTIFICATE SIGN REQUEST

### ISSUE THREAD

**Issue by yunusemreayhan** [intel/tpm2-tools#756]
Would you please provide a tool creates CSR (Certificate Signing Request) using tpm 2.0 created rsa pair, maybe in collobration with openssl.
  
Thanks in advance.

**Comment by emmanuel-deloget** [comment]
Related to this, I'm currently working on expending the tpm2-pk11 pkcs11 provider to do just that (and many other things). I should be able to produce patches to this project in a few days (and then, you'll be able to openssl req -new right after :)

Best regards,

-- Emmanuel Deloget
