### ISSUE TITLE
bootstrap script fails when used from tpm2-tools.zip

### ISSUE THREAD

**Issue by pscheie** [intel/tpm2-tools#771]
I downloaded the tpm2-tools.zip rather than git cloning because I have to move the files over to an air-gapped network and this is easier with a single zip file.  But after unzipping the file on the air-gapped host, bootstrap fails with all sorts of fatal complaints about 'Not a git repository'.  INSTALL says use git clone to get the source files.  Does the zip file actually work?

**Comment by williamcroberts** [comment]
Zips do not work. You can do make dist to make a tarball that will work.
If you want a release version, dist tarballs are available under the releases for newer releases.

**Comment by pscheie** [comment]
So, just to clarify, downloading the zip file from github and trying to build with the contents of that does not work?  If so, why does the zip file exist?

**Comment by williamcroberts** [comment]
The zip file is a github feature, I haven't found a way to disable that.
