### ISSUE TITLE
How do I load the OpenSSL private key into the TPM2?

### ISSUE THREAD

**Issue by searchmawnag** [intel/tpm2-tools#774]
I wanted load the OpenSSL private key into the TPM2 Device.

I found the source to change to structure of TPM2B_PRIVATE using the IBMTSS based OpenSSL private key.
-> https://github.com/manoj23/pemtpm

How do I change the OpenSSL private key to the structure of TPM2B_PRIVATE based on INTELTSS?

Help Me.

Thank you.

**Comment by williamcroberts** [comment]
You can look at tpm2_import and its tests under test/system/tests/disabled

Right now, both are not working.

There is also conversion.h that should have the routines you need or can follow along with.

Questions like this should go to the mailing list, not our bug/feature tracker.
